server:
  port: 8085

spring:
  application:
    name: rabbit-admin
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:rabbitmq-1:5672,rabbitmq-2:5672}
    username: ${SPRING_RABBITMQ_USERNAME:colegio_app}
    password: ${SPRING_RABBITMQ_PASSWORD:colegio_app}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
        prefetch: 1

rabbitmq:
  management:
    url: http://${RABBIT_MANAGEMENT_HOST:rabbitmq-1}:15672/api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
