server:
  port: 8085

spring:
  application:
    name: rabbit-admin
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
        prefetch: 1

rabbitmq:
  management:
    url: http://${RABBIT_HOST:localhost}:15672/api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
